### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Nivedita967** [virejdasani/Responsivize#3]
1. Toggle dark mode/ light mode button.
2. Back to top button.
3. Images are left aligned, to be centered.

Would like to work on UI improvement on this website.

![Screenshot (175)](https://user-images.githubusercontent.com/66518355/129910627-1ba1ad0e-77c2-47fc-a353-00a5627f3860.png)

**Comment by virejdasani** [comment]
Go ahead and make a pull request, I'll merge it!
