### ISSUE TITLE
Add `https://` to URLs when searching.

### ISSUE THREAD

**Issue by kazuhitonakayama** [virejdasani/Responsivize#7]
## Overview
Now, when searching site, we must add `https://` to URL.
But is it more useful that we can be search URL without `https://`?

### Without `https://`
![image](https://user-images.githubusercontent.com/50609459/131621461-974ac608-9ab5-4702-bb3e-2a488e184334.png)

### With `https://`
![image](https://user-images.githubusercontent.com/50609459/131621530-e981cc6f-abae-47ec-b61a-17e0b7477522.png)

**Comment by kazuhitonakayama** [comment]
@Nivedita967 @virejdasani 
Nice to meet you 🙇  
Thank you for your awesome product `Responsivize`！
I want to talk with you about this issue (I want to talk to you about what your intentions are for the current specifications.)

**Comment by virejdasani** [comment]
Hi @kazuhitonakayama, thanks for bringing this to my attention, I'll get this fixed and put an update out asap :)

Also, I @virejdasani am the maintainer of Responsivize, Nivedita967 once made some changes to an older version of the Responsivize website and is just a contributor so I'd ask you to not mention her.

**Comment by virejdasani** [comment]
> Can I also work on this issue...?

Sure, I'll assign you. You can create a PR and I'll merge it :)

**Comment by kazuhitonakayama** [comment]
> > Can I also work on this issue...?
> 
> Sure, I'll assign you. You can create a PR and I'll merge it :)

Thank you for your sincerity :)

**Comment by virejdasani** [comment]
#9
