### ISSUE TITLE
Basic Authentication support

### ISSUE THREAD

**Issue by nabedge** [virejdasani/Responsivize#8]
Hi. 
Responsivize is so COOL !

So, please support Basic Authentication because my development environment needs it. :-)

**Comment by virejdasani** [comment]
Hi @nabedge, I'm glad you liked it! 
I'm sorry but I'm not familiar with Basic Authentication in development environments :(
If you want, you can fork the repo and implement it. I'll go ahead and merge it :)

**Comment by virejdasani** [comment]
Closing because of no reply
